// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY0E4cPP2Nw_1Zieu3p7nnW7lo-O_RGjg',
    appId: '1:869153437004:web:8cede0c849344bea2dcbe9',
    messagingSenderId: '869153437004',
    projectId: 'guiaturisticosr',
    authDomain: 'guiaturisticosr.firebaseapp.com',
    storageBucket: 'guiaturisticosr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuiUji-EBI_XiNlDGEUXWDP9ThWBvzseI',
    appId: '1:869153437004:android:5247656efef6ac982dcbe9',
    messagingSenderId: '869153437004',
    projectId: 'guiaturisticosr',
    storageBucket: 'guiaturisticosr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW790JtzBlmhZxXiH42cM-Yc5T15aZpww',
    appId: '1:869153437004:ios:94de9badbad640082dcbe9',
    messagingSenderId: '869153437004',
    projectId: 'guiaturisticosr',
    storageBucket: 'guiaturisticosr.firebasestorage.app',
    iosClientId: '869153437004-fn7hna93geid1dkgkssfp1btfq4dq3ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.guiaturisticosr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW790JtzBlmhZxXiH42cM-Yc5T15aZpww',
    appId: '1:869153437004:ios:94de9badbad640082dcbe9',
    messagingSenderId: '869153437004',
    projectId: 'guiaturisticosr',
    storageBucket: 'guiaturisticosr.firebasestorage.app',
    iosClientId: '869153437004-fn7hna93geid1dkgkssfp1btfq4dq3ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.guiaturisticosr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY0E4cPP2Nw_1Zieu3p7nnW7lo-O_RGjg',
    appId: '1:869153437004:web:57d1972a04d781e32dcbe9',
    messagingSenderId: '869153437004',
    projectId: 'guiaturisticosr',
    authDomain: 'guiaturisticosr.firebaseapp.com',
    storageBucket: 'guiaturisticosr.firebasestorage.app',
  );

}