// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-rec7i6TwYLmtiKF3GEF4oGNl1OGRdI',
    appId: '1:383445250997:web:664ca2d4415ba1a299dffc',
    messagingSenderId: '383445250997',
    projectId: 'guia-turistico-sr-jacke',
    authDomain: 'guia-turistico-sr-jacke.firebaseapp.com',
    storageBucket: 'guia-turistico-sr-jacke.firebasestorage.app',
    measurementId: 'G-GMQ4F27E5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kJEDc6PKStN1GvmUx56OtyHpsQ1W9fA',
    appId: '1:383445250997:android:7f9c8fb3d3c0471699dffc',
    messagingSenderId: '383445250997',
    projectId: 'guia-turistico-sr-jacke',
    storageBucket: 'guia-turistico-sr-jacke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVsTrLP60NkJbnG7f1y8utS4BWOJtlUw',
    appId: '1:383445250997:ios:eeaa7c00d9f2658e99dffc',
    messagingSenderId: '383445250997',
    projectId: 'guia-turistico-sr-jacke',
    storageBucket: 'guia-turistico-sr-jacke.firebasestorage.app',
    iosBundleId: 'com.example.guiaturisticosr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVsTrLP60NkJbnG7f1y8utS4BWOJtlUw',
    appId: '1:383445250997:ios:eeaa7c00d9f2658e99dffc',
    messagingSenderId: '383445250997',
    projectId: 'guia-turistico-sr-jacke',
    storageBucket: 'guia-turistico-sr-jacke.firebasestorage.app',
    iosBundleId: 'com.example.guiaturisticosr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-rec7i6TwYLmtiKF3GEF4oGNl1OGRdI',
    appId: '1:383445250997:web:796586035fc99a1099dffc',
    messagingSenderId: '383445250997',
    projectId: 'guia-turistico-sr-jacke',
    authDomain: 'guia-turistico-sr-jacke.firebaseapp.com',
    storageBucket: 'guia-turistico-sr-jacke.firebasestorage.app',
    measurementId: 'G-3ZCRKCQ76D',
  );
}
